### ISSUE TITLE
textlint --fix doen't work correctly.

### ISSUE THREAD

**Issue by tani** [textlint-rule/textlint-rule-ginger#77]
This plugin fails in this case

```
I love you.
I has a pens.
```

I guess the reason is that this library calculate position to fix by the column.

**Comment by tani** [comment]
const originalRange = [
              originalPosition.column,
              originalPosition.column + correction.length,
            ];

**Comment by azu** [comment]
We would use [originalIndexFromIndex(generatedIndex): number](https://github.com/textlint/textlint-util-to-string#originalindexfromindexgeneratedindex-number) instead of `originalPositionFromIndex`?

https://github.com/textlint-rule/textlint-rule-ginger/blob/3f65ef822ea8d1936793830673ba91e713ea868e/src/ginger.js#L72-L76

**Comment by tani** [comment]
Yes, it's better way. Now I testing it locally. Please wait few minutes...

**Comment by tani** [comment]
It passed exists tests, now I add a test case for this issue.

**Comment by tani** [comment]
I added them, thank you.
